#Main page
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bobagang.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from login import Ui_LoginWindow

class Ui_Form(object):
    def open_LoginWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LoginWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 740)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 561, 741))
        self.stackedWidget.setStyleSheet("QWidget#name{background-color: rgb(157, 234, 255);}\n"
"QWidget#welcome{background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0508475 rgba(255, 101, 101, 255), stop:1 rgba(232, 224, 150, 255));}\n"
"QWidget#menu{background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0508475 rgba(83, 136, 255, 255), stop:1 rgba(166, 232, 232, 255));}\n"
"QWidget#basket{background-color: rgb(255, 225, 135);}\n"
"QWidget#payment{background-color: rgb(255, 225, 135);}\n"
"QWidget#paid{background-color: rgb(254, 166, 168);}\n"
"QWidget#ready{background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.0508475 rgba(255, 101, 101, 255), stop:1 rgba(232, 224, 150, 255));}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome = QtWidgets.QWidget()
        self.welcome.setObjectName("welcome")
        self.label_2 = QtWidgets.QLabel(self.welcome)
        self.label_2.setGeometry(QtCore.QRect(220, 180, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(44)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("\n"
"font: 75 44pt \"Bahnschrift Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.Next_button = QtWidgets.QPushButton(self.welcome)
        self.Next_button.setGeometry(QtCore.QRect(160, 500, 241, 131))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Next_button.setFont(font)
        self.Next_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Next_button.setStyleSheet("font: 36pt \"Bahnschrift Condensed\";\n"
"background-color: rgb(235, 107, 86);")
        self.Next_button.setAutoRepeatDelay(300)
        self.Next_button.setObjectName("Next_button")
        self.label = QtWidgets.QLabel(self.welcome)
        self.label.setGeometry(QtCore.QRect(65, 270, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(44)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("\n"
"font: 75 44pt \"Bahnschrift Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        
#Seller_button
#go to login
        self.Seller_button = QtWidgets.QPushButton(self.welcome, clicked = lambda : self.open_LoginWindow())
        self.Seller_button.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.Seller_button.setStyleSheet("\n"
"font: 75 15pt \"Bahnschrift Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 58, 108);")
        self.Seller_button.setObjectName("Seller_button")
        self.stackedWidget.addWidget(self.welcome)
        self.name = QtWidgets.QWidget()
        self.name.setObjectName("name")
        self.Back_button_2 = QtWidgets.QPushButton(self.name)
        self.Back_button_2.setGeometry(QtCore.QRect(30, 660, 121, 61))
        self.Back_button_2.setStyleSheet("\n"
"background-color: rgb(131, 67, 131);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Back_button_2.setObjectName("Back_button_2")
        self.label_3 = QtWidgets.QLabel(self.name)
        self.label_3.setGeometry(QtCore.QRect(70, 170, 421, 71))
        self.label_3.setStyleSheet("font: 48pt \"Bahnschrift Condensed\"")
        self.label_3.setObjectName("label_3")
        self.Next_button_2 = QtWidgets.QPushButton(self.name)
        self.Next_button_2.setGeometry(QtCore.QRect(415, 660, 121, 61))
        self.Next_button_2.setStyleSheet("background-color: rgb(176, 95, 109);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Next_button_2.setObjectName("Next_button_2")
        self.lineEdit = QtWidgets.QLineEdit(self.name)
        self.lineEdit.setGeometry(QtCore.QRect(60, 300, 441, 51))
        self.lineEdit.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.stackedWidget.addWidget(self.name)
        self.menu = QtWidgets.QWidget()
        self.menu.setObjectName("menu")
        self.bla_s = QtWidgets.QPushButton(self.menu)
        self.bla_s.setGeometry(QtCore.QRect(140, 370, 51, 31))
        self.bla_s.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.bla_s.setObjectName("bla_s")
        self.ori_s = QtWidgets.QPushButton(self.menu)
        self.ori_s.setGeometry(QtCore.QRect(140, 180, 51, 31))
        self.ori_s.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.ori_s.setObjectName("ori_s")
        self.label_13 = QtWidgets.QLabel(self.menu)
        self.label_13.setGeometry(QtCore.QRect(410, 520, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 18pt \"Bahnschrift Condensed\";")
        self.label_13.setObjectName("label_13")
        self.bro_s = QtWidgets.QPushButton(self.menu)
        self.bro_s.setGeometry(QtCore.QRect(400, 180, 51, 31))
        self.bro_s.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.bro_s.setObjectName("bro_s")
        self.choc_s = QtWidgets.QPushButton(self.menu)
        self.choc_s.setGeometry(QtCore.QRect(400, 370, 51, 31))
        self.choc_s.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.choc_s.setObjectName("choc_s")
        self.thai_s = QtWidgets.QPushButton(self.menu)
        self.thai_s.setGeometry(QtCore.QRect(140, 560, 51, 31))
        self.thai_s.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.thai_s.setObjectName("thai_s")
        self.Next_button_3 = QtWidgets.QPushButton(self.menu)
        self.Next_button_3.setGeometry(QtCore.QRect(415, 660, 121, 61))
        self.Next_button_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Next_button_3.setStyleSheet("background-color: rgb(176, 95, 109);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Next_button_3.setObjectName("Next_button_3")
        self.label_18 = QtWidgets.QLabel(self.menu)
        self.label_18.setGeometry(QtCore.QRect(200, 560, 21, 31))
        self.label_18.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.label_5 = QtWidgets.QLabel(self.menu)
        self.label_5.setGeometry(QtCore.QRect(0, 470, 170, 170))
        self.label_5.setStyleSheet("image: url(:/newPrefix/Downloads/Thai-Tea.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.mat_s = QtWidgets.QPushButton(self.menu)
        self.mat_s.setGeometry(QtCore.QRect(400, 560, 51, 31))
        self.mat_s.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.mat_s.setObjectName("mat_s")
        self.label_8 = QtWidgets.QLabel(self.menu)
        self.label_8.setGeometry(QtCore.QRect(130, 140, 151, 41))
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 18pt \"Bahnschrift Condensed\";")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.menu)
        self.label_11.setGeometry(QtCore.QRect(400, 330, 131, 41))
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 18pt \"Bahnschrift Condensed\";")
        self.label_11.setObjectName("label_11")
        self.label_17 = QtWidgets.QLabel(self.menu)
        self.label_17.setGeometry(QtCore.QRect(460, 370, 21, 31))
        self.label_17.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.label_6 = QtWidgets.QLabel(self.menu)
        self.label_6.setGeometry(QtCore.QRect(0, 280, 170, 170))
        self.label_6.setStyleSheet("image: url(:/newPrefix/Downloads/Black-Tea.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.menu)
        self.label_15.setGeometry(QtCore.QRect(200, 370, 21, 31))
        self.label_15.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.menu)
        self.label_16.setGeometry(QtCore.QRect(460, 180, 21, 31))
        self.label_16.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_12 = QtWidgets.QLabel(self.menu)
        self.label_12.setGeometry(QtCore.QRect(155, 520, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 18pt \"Bahnschrift Condensed\";")
        self.label_12.setObjectName("label_12")
        self.mat_m = QtWidgets.QPushButton(self.menu)
        self.mat_m.setGeometry(QtCore.QRect(480, 560, 51, 31))
        self.mat_m.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.mat_m.setObjectName("mat_m")
        self.bla_m = QtWidgets.QPushButton(self.menu)
        self.bla_m.setGeometry(QtCore.QRect(220, 370, 51, 31))
        self.bla_m.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.bla_m.setObjectName("bla_m")
        self.choc_m = QtWidgets.QPushButton(self.menu)
        self.choc_m.setGeometry(QtCore.QRect(480, 370, 51, 31))
        self.choc_m.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.choc_m.setObjectName("choc_m")
        self.label_9 = QtWidgets.QLabel(self.menu)
        self.label_9.setGeometry(QtCore.QRect(395, 140, 151, 41))
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 18pt \"Bahnschrift Condensed\";")
        self.label_9.setObjectName("label_9")
        self.label_20 = QtWidgets.QLabel(self.menu)
        self.label_20.setGeometry(QtCore.QRect(220, 30, 131, 61))
        self.label_20.setStyleSheet("\n"
"font: 54pt \"Bahnschrift Condensed\";\n"
"color: rgb(255,255,255);")
        self.label_20.setObjectName("label_20")
        self.ori_m = QtWidgets.QPushButton(self.menu)
        self.ori_m.setGeometry(QtCore.QRect(220, 180, 51, 31))
        self.ori_m.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.ori_m.setObjectName("ori_m")
        self.label_19 = QtWidgets.QLabel(self.menu)
        self.label_19.setGeometry(QtCore.QRect(460, 560, 21, 31))
        self.label_19.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.Back_button_3 = QtWidgets.QPushButton(self.menu)
        self.Back_button_3.setGeometry(QtCore.QRect(30, 660, 121, 61))
        self.Back_button_3.setStyleSheet("\n"
"background-color: rgb(131, 67, 131);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Back_button_3.setObjectName("Back_button_3")
        self.label_7 = QtWidgets.QLabel(self.menu)
        self.label_7.setGeometry(QtCore.QRect(0, 90, 170, 170))
        self.label_7.setStyleSheet("image: url(:/newPrefix/Downloads/Bobagang-Original.png);\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.menu)
        self.label_10.setGeometry(QtCore.QRect(170, 330, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 18pt \"Bahnschrift Condensed\";")
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.menu)
        self.label_14.setGeometry(QtCore.QRect(260, 470, 170, 170))
        self.label_14.setStyleSheet("image: url(:/newPrefix/Downloads/Matcha.png);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_21 = QtWidgets.QLabel(self.menu)
        self.label_21.setGeometry(QtCore.QRect(260, 90, 170, 170))
        self.label_21.setStyleSheet("image: url(:/newPrefix/Downloads/Brown-Sugar.png);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.menu)
        self.label_22.setGeometry(QtCore.QRect(260, 280, 170, 170))
        self.label_22.setStyleSheet("image: url(:/newPrefix/Downloads/Chocolate-.png);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.thai_m = QtWidgets.QPushButton(self.menu)
        self.thai_m.setGeometry(QtCore.QRect(220, 560, 51, 31))
        self.thai_m.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.thai_m.setObjectName("thai_m")
        self.label_23 = QtWidgets.QLabel(self.menu)
        self.label_23.setGeometry(QtCore.QRect(200, 180, 21, 31))
        self.label_23.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.bro_m = QtWidgets.QPushButton(self.menu)
        self.bro_m.setGeometry(QtCore.QRect(480, 180, 51, 31))
        self.bro_m.setStyleSheet("background-color: rgb(250, 193, 114);")
        self.bro_m.setObjectName("bro_m")
        self.label_24 = QtWidgets.QLabel(self.menu)
        self.label_24.setGeometry(QtCore.QRect(215, 30, 131, 61))
        self.label_24.setStyleSheet("\n"
"font: 54pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_24.setObjectName("label_24")
        self.stackedWidget.addWidget(self.menu)
        self.basket = QtWidgets.QWidget()
        self.basket.setObjectName("basket")
        self.label_4 = QtWidgets.QLabel(self.basket)
        self.label_4.setGeometry(QtCore.QRect(150, 210, 271, 51))
        self.label_4.setStyleSheet("font: 35pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_4.setObjectName("label_4")
        self.label_25 = QtWidgets.QLabel(self.basket)
        self.label_25.setGeometry(QtCore.QRect(250, 560, 91, 41))
        self.label_25.setStyleSheet("font: 32pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_25.setObjectName("label_25")
        self.Back_button_6 = QtWidgets.QPushButton(self.basket)
        self.Back_button_6.setGeometry(QtCore.QRect(30, 660, 121, 61))
        self.Back_button_6.setStyleSheet("\n"
"background-color: rgb(131, 67, 131);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Back_button_6.setObjectName("Back_button_6")
        self.confirm_button = QtWidgets.QPushButton(self.basket)
        self.confirm_button.setGeometry(QtCore.QRect(385, 640, 141, 81))
        self.confirm_button.setStyleSheet("background-color: rgb(137, 213, 201);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.confirm_button.setObjectName("confirm_button")
        self.label_26 = QtWidgets.QLabel(self.basket)
        self.label_26.setGeometry(QtCore.QRect(200, 60, 161, 61))
        self.label_26.setStyleSheet("font: 54pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.basket)
        self.label_27.setGeometry(QtCore.QRect(35, 160, 491, 31))
        self.label_27.setStyleSheet("font: 24pt \"Bahnschrift Condensed\";\n"
"color: rgb(170, 0, 0);")
        self.label_27.setObjectName("label_27")
        self.total = QtWidgets.QLabel(self.basket)
        self.total.setGeometry(QtCore.QRect(370, 540, 111, 41))
        self.total.setText("")
        self.total.setObjectName("total")
        self.yourorder_list = QtWidgets.QListWidget(self.basket)
        self.yourorder_list.setGeometry(QtCore.QRect(60, 270, 441, 271))
        self.yourorder_list.setObjectName("yourorder_list")
        self.stackedWidget.addWidget(self.basket)
        self.payment = QtWidgets.QWidget()
        self.payment.setObjectName("payment")
        self.label_28 = QtWidgets.QLabel(self.payment)
        self.label_28.setGeometry(QtCore.QRect(34, 90, 491, 81))
        self.label_28.setStyleSheet("font: 30pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_28.setObjectName("label_28")
        self.Back_button_5 = QtWidgets.QPushButton(self.payment)
        self.Back_button_5.setGeometry(QtCore.QRect(30, 660, 121, 61))
        self.Back_button_5.setStyleSheet("\n"
"background-color: rgb(131, 67, 131);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Back_button_5.setObjectName("Back_button_5")
        self.confirm_button_2 = QtWidgets.QPushButton(self.payment)
        self.confirm_button_2.setGeometry(QtCore.QRect(385, 640, 141, 81))
        self.confirm_button_2.setStyleSheet("background-color: rgb(137, 213, 201);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.confirm_button_2.setObjectName("confirm_button_2")
        self.stackedWidget.addWidget(self.payment)
        self.paid = QtWidgets.QWidget()
        self.paid.setObjectName("paid")
        self.label_29 = QtWidgets.QLabel(self.paid)
        self.label_29.setGeometry(QtCore.QRect(75, 240, 421, 71))
        self.label_29.setStyleSheet("font: 45pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.paid)
        self.label_30.setGeometry(QtCore.QRect(165, 420, 221, 61))
        self.label_30.setStyleSheet("font: 28pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.paid)
        self.label_31.setGeometry(QtCore.QRect(105, 370, 351, 61))
        self.label_31.setStyleSheet("font: 28pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_31.setObjectName("label_31")
        self.stackedWidget.addWidget(self.paid)
        self.ready = QtWidgets.QWidget()
        self.ready.setObjectName("ready")
        self.label_32 = QtWidgets.QLabel(self.ready)
        self.label_32.setGeometry(QtCore.QRect(85, 190, 391, 71))
        self.label_32.setStyleSheet("font: 45pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.ready)
        self.label_33.setGeometry(QtCore.QRect(85, 470, 391, 61))
        self.label_33.setStyleSheet("font: 22pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.ready)
        self.label_34.setGeometry(QtCore.QRect(185, 520, 191, 41))
        self.label_34.setStyleSheet("font: 22pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_34.setObjectName("label_34")
        self.customer_name = QtWidgets.QLabel(self.ready)
        self.customer_name.setGeometry(QtCore.QRect(10, 330, 541, 81))
        self.customer_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.customer_name.setStyleSheet("font: 45pt \"Bahnschrift Condensed\";\n"
"color: rgb(51, 58, 108);\n"
"")
        self.customer_name.setText("")
        self.customer_name.setAlignment(QtCore.Qt.AlignCenter)
        self.customer_name.setObjectName("customer_name")
        self.label_35 = QtWidgets.QLabel(self.ready)
        self.label_35.setGeometry(QtCore.QRect(145, 560, 261, 41))
        self.label_35.setStyleSheet("font: 22pt \"Bahnschrift Condensed\";\n"
"color: rgb(0,0,0);")
        self.label_35.setObjectName("label_35")
        self.stackedWidget.addWidget(self.ready)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Hello!!"))
        self.Next_button.setText(_translate("Form", "NEXT"))
        self.label.setText(_translate("Form", "Welcome to BobaGang"))
        self.Seller_button.setText(_translate("Form", "For sellers"))
        self.Back_button_2.setText(_translate("Form", "Back"))
        self.label_3.setText(_translate("Form", "What is your name?"))
        self.Next_button_2.setText(_translate("Form", "Next"))
        self.bla_s.setText(_translate("Form", "S  55"))
        self.ori_s.setText(_translate("Form", "S  65"))
        self.label_13.setText(_translate("Form", "Matcha Latte"))
        self.bro_s.setText(_translate("Form", "S  70"))
        self.choc_s.setText(_translate("Form", "S  65"))
        self.thai_s.setText(_translate("Form", "S  65"))
        self.Next_button_3.setText(_translate("Form", "Next"))
        self.label_18.setText(_translate("Form", "/"))
        self.mat_s.setText(_translate("Form", "S  80"))
        self.label_8.setText(_translate("Form", "Boba gang Original"))
        self.label_11.setText(_translate("Form", "Chocolate Latte"))
        self.label_17.setText(_translate("Form", "/"))
        self.label_15.setText(_translate("Form", "/"))
        self.label_16.setText(_translate("Form", "/"))
        self.label_12.setText(_translate("Form", "Thai milk tea"))
        self.mat_m.setText(_translate("Form", "M  90"))
        self.bla_m.setText(_translate("Form", "M  65"))
        self.choc_m.setText(_translate("Form", "M  75"))
        self.label_9.setText(_translate("Form", "Brown sugar milk"))
        self.label_20.setText(_translate("Form", "Menu"))
        self.ori_m.setText(_translate("Form", "M  75"))
        self.label_19.setText(_translate("Form", "/"))
        self.Back_button_3.setText(_translate("Form", "Back"))
        self.label_10.setText(_translate("Form", "Black tea"))
        self.thai_m.setText(_translate("Form", "M  75"))
        self.label_23.setText(_translate("Form", "/"))
        self.bro_m.setText(_translate("Form", "M  80"))
        self.label_24.setText(_translate("Form", "Menu"))
        self.label_4.setText(_translate("Form", "Your order today :"))
        self.label_25.setText(_translate("Form", "Total ="))
        self.Back_button_6.setText(_translate("Form", "Back"))
        self.confirm_button.setText(_translate("Form", "Confirm"))
        self.label_26.setText(_translate("Form", "Basket"))
        self.label_27.setText(_translate("Form", "*Please check your order before click confirm."))
        self.label_28.setText(_translate("Form", "Please scan QR code for the payment"))
        self.Back_button_5.setText(_translate("Form", "Back"))
        self.confirm_button_2.setText(_translate("Form", "Confirm"))
        self.label_29.setText(_translate("Form", "Payment Completed !"))
        self.label_30.setText(_translate("Form", "the order is ready."))
        self.label_31.setText(_translate("Form", "We will call your name when"))
        self.label_32.setText(_translate("Form", "Your order is ready!"))
        self.label_33.setText(_translate("Form", "Please receive your drink at the counter"))
        self.label_34.setText(_translate("Form", " and enjoy the meal"))
        self.label_35.setText(_translate("Form", "Welcome back again soon :)"))
import testt


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
