#LoginWindow for sellers
#Seperate window
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(560, 740)
        LoginWindow.setStyleSheet("QWidget#centralwidget{background-color: rgb(51, 58, 108);}")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 60, 151, 81))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 48pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 270, 201, 31))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 420, 201, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 170, 381, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.Back_button = QtWidgets.QPushButton(self.centralwidget)
        self.Back_button.setGeometry(QtCore.QRect(30, 660, 121, 61))
        self.Back_button.setStyleSheet("\n"
"background-color: rgb(131, 67, 131);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Back_button.setObjectName("Back_button")
        self.Next_button = QtWidgets.QPushButton(self.centralwidget)
        self.Next_button.setGeometry(QtCore.QRect(415, 660, 121, 61))
        self.Next_button.setStyleSheet("background-color: rgb(176, 95, 109);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Next_button.setObjectName("Next_button")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 340, 461, 50))
        self.lineEdit.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 480, 461, 50))
        self.lineEdit_2.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "Login"))
        self.label_2.setText(_translate("LoginWindow", "User name :"))
        self.label_3.setText(_translate("LoginWindow", "Password :"))
        self.label_4.setText(_translate("LoginWindow", "THIS IS FOR SELLERS ONLY !!!!"))
        self.Back_button.setText(_translate("LoginWindow", "Back"))
        self.Next_button.setText(_translate("LoginWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
